# LED Lighting Events
# Format: (time_ms, strip_index, brightness, effect, duration_ms)
# Effects: strobe, flash, pulse, fade, hold, wave
#
# This is a sample/demo event file
# Replace with your own events generated by lights_tool.py

events = [
    # Demo: All effects on different strips
    # Time 0-500ms: Flash on strip 0
    (0, 0, 255, "flash", 500),
    
    # 500ms: Pulse on strip 1
    (500, 1, 200, "pulse", 800),
    
    # 1000ms: Strobe on strip 2
    (1000, 2, 255, "strobe", 300),
    
    # 1500ms: Fade on strip 3
    (1500, 3, 180, "fade", 1000),
    
    # 2000ms: Hold on strip 4
    (2000, 4, 200, "hold", 1500),
    
    # 3000ms: Wave on strip 0
    (3000, 0, 220, "wave", 2000),
    
    # 4000ms: Multiple strips at once
    (4000, 0, 255, "pulse", 1000),
    (4000, 2, 255, "pulse", 1000),
    (4000, 4, 255, "pulse", 1000),
    
    # 5500ms: Alternating pattern
    (5500, 1, 200, "flash", 300),
    (5800, 3, 200, "flash", 300),
    (6100, 1, 200, "flash", 300),
    (6400, 3, 200, "flash", 300),
    
    # 7000ms: All strips wave
    (7000, 0, 180, "wave", 2000),
    (7200, 1, 180, "wave", 2000),
    (7400, 2, 180, "wave", 2000),
    (7600, 3, 180, "wave", 2000),
    (7800, 4, 180, "wave", 2000),
    
    # 10000ms: Grand finale - all strips
    (10000, 0, 255, "strobe", 500),
    (10000, 1, 255, "strobe", 500),
    (10000, 2, 255, "strobe", 500),
    (10000, 3, 255, "strobe", 500),
    (10000, 4, 255, "strobe", 500),
    
    (10600, 0, 255, "fade", 1500),
    (10600, 1, 255, "fade", 1500),
    (10600, 2, 255, "fade", 1500),
    (10600, 3, 255, "fade", 1500),
    (10600, 4, 255, "fade", 1500),
]
